### ISSUE TITLE
No Ip-address set

### ISSUE THREAD

**Issue by Ridesa** [forelleblau/ioBroker.solarlog#1]
Meldung kommt nach dem ich meine IP Adresse eingebe und den Adapter starte :/ 

solarlog.0 | 2018-11-07 20:23:43.092 | warn | [START] No IP-address set
-- | -- | -- | --

**Comment by forelleblau** [comment]
Hallo 

 

Danke fürs Testen und für die Rückmeldung

 

Kannst du mir sagen, ob die IP im «native» Reiter bei den Eigenschaften des Instance-Objekts eingetragen ist?

 

 

 

 



 

 

Beste Grüsse

 

Marcel Adam

 

 

Von: Ridesa <notifications@github.com> 
Gesendet: Mittwoch, 7. November 2018 20:27
An: forelleblau/ioBroker.solarlog <ioBroker.solarlog@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Betreff: [forelleblau/ioBroker.solarlog] No Ip-address set (#1)

 

Meldung kommt nach dem ich meine IP Adresse eingebe und den Adapter starte :/


solarlog.0

2018-11-07 20:23:43.092

warn

[START] No IP-address set

**Comment by forelleblau** [comment]
Mögliche Fehlerquelle gefunden und behoben (falsche Variablendeklaration in index_m.html).

**Comment by forelleblau** [comment]
Fehler ist behoben.
