### ISSUE TITLE
Batteriedaten auslesen

### ISSUE THREAD

**Issue by gepe2810** [forelleblau/ioBroker.solarlog#15]
Hallo forelleblau,
ich bin Gepe000 aus dem ioBroker Forum. Gemäß deiner Anleitung hab ich mal ein wenig recherchiert. Das Konfigurationsmenü gibt nicht viel her - jedenfalls sagt mir der Inhalt nicht. Hier sind die Hardcopies dazu:

Konfiguration - Definition:
![Definition](https://user-images.githubusercontent.com/35432588/66112740-b6d45000-e5cb-11e9-8c68-b0be6bf020ed.jpg)

Konfiguration - Erkennung:
![Erkennung](https://user-images.githubusercontent.com/35432588/66112756-bf2c8b00-e5cb-11e9-91dd-a37fef70a80a.jpg)

Konfiguration - Konfiguration:
![Konfiguration1](https://user-images.githubusercontent.com/35432588/66112783-cbb0e380-e5cb-11e9-9cb5-1c84949b5cf6.jpg)

![Konfiguration2](https://user-images.githubusercontent.com/35432588/66112802-d23f5b00-e5cb-11e9-8f89-7c4d75b4c4c3.jpg)

![Konfiguration3](https://user-images.githubusercontent.com/35432588/66112819-d9666900-e5cb-11e9-8a83-b7dbeaddfc97.jpg)

Ein paar Informationen, die der Adapter bisher noch nicht anzeigt, finden sich im Bilanz-Menü. Da ich schon mal dabei war, habe ich die Analyse auch gleich dafür erstellt:

![Bilanz](https://user-images.githubusercontent.com/35432588/66113009-34985b80-e5cc-11e9-8ebf-7f15379caa2c.jpg)

Dabei sind die Daten so zu interpretieren:
777.0:
- Wert1 = ?
- Wert2 = Heizstab
- Wert3 = Erzeugung
- Wert4 = Verbrauch 

778.0:
- Wert1 = Eigenverbrauch
- Wert2 = Eigenverbrauch Batterie
- Wert3 = Ladung Batterie
- Wert4 = Entladung Batterie

**Comment by forelleblau** [comment]
Danke vielmals für die Analysen. In der Konfiguration könnte doch der Typ drinstecken:
141.X.145. Dann wäre 6= Batterie, 7= Heizstab, 0= Wechselrichter,... vielleicht findet sich ja dieser Code irgendwo, z.B. in der Programmierung zum Dropdown-Menü bei Konfiguration-Konfiguration o.ä.
Das 777er Objekt wird übrigens schon abgefragt, das findest du im logfile von dir. Die Werte solltest du bei INV/Gerät/daysum wiederfinden. Aber jeweils nur die aktuellen Tagessummen, nicht die Historie.  Dass 778 aber zur Batterie gehört ist wertvoll, Danke, da kann ich drauf aufbauen.

**Comment by forelleblau** [comment]
Hier https://github.com/forelleblau/ioBroker.solarlog/blob/master/docs/solarlog_dataobjects.md findest du übrigens die bisher ergründeten Objekte aus dem solarlog - bei Interesse.

**Comment by forelleblau** [comment]
Hallo Gepe000
Ich habs gefunden! Ist etwas verschachtelt:
Im 141.X.162 ist der Gerätetyp (Modell) hinterlegt. Dazu gibt es ein Objekt 739, in dem alle Gerätetypen hinterlegt sind, die angeschlossen werden können (so verstehe ich es jedenfalls). Und mit dem Wert 739.(141.X.162).5 ist dann die Geräteklasse definiert, deren Schlüssel im Pulldownmenu fürs Anlegen neuer Geräte versteckt war:
![image](https://user-images.githubusercontent.com/44144152/66259866-45f18b80-e7b7-11e9-8a4b-d460eb98b58e.png)

So könnte man also herausfinden, ob ein Gerät eine Batterie ist oder etwas anderes.
Das dem Adapter beibringen mache ich nicht mehr heute Abend, aber werde mich dran machen, die neu gewonnenen Erkenntnisse umzusetzen.
Herzliche Grüsse
Forelleblau

**Comment by gepe2810** [comment]
Im Auswahlmenü Konfiguration-Definition werden folgende Geräte angeboten:
- Batterie
- Heizstab
- Hybrid-System
- Intelligente Verbraucher
- Ladestation
- Schalter
- Sensor
- Wechselrichter
- Wärmepumpe
- Zähler

ich finde sie nur nicht in der Ausgabe des Entwicklertools

**Comment by gepe2810** [comment]
Im Auswahlmenü Konfiguration-Definition werden folgende Geräte angeboten:

Batterie
Heizstab
Hybrid-System
Intelligente Verbraucher
Ladestation
Schalter
Sensor
Wechselrichter
Wärmepumpe
Zähler
ich finde sie nur nicht in der Ausgabe des Entwicklertools

**Comment by forelleblau** [comment]
Du musst im Entwicklertool zu 'Elements' (oben) wechseln, wenn du das Auswahlfenster offen hast. Wenn du dich dann durch die divs durchklickst findest du irgenwann das, dass das Auswahlfeld beschreibt - das welches du oben im Bild siehst.

**Comment by forelleblau** [comment]
Hallo
Habe eben eine recht überarbeitete Version auf Github hochgeladen (1.0.0). 
Diese liest jetzt Geräteklassen, -typen und -marken aus und ist dadurch in der Lage (oder sollte es sein) die Objekte für Batterien korrekt anzulegen. Bei Kombigeräten sollte ein generischen Gerät "Batterie" im INV-Channel angelegt und mit den Werten bestückt werden (-> z.B. @philoxio).
Der Adapter ist zudem in der Datenabfrage etwas anders struktuiert - hoffentlich verbessert.
Bei meinem batteriefreien System funktioniert alles korrekt und ich habe soweit ich das kann auch versucht gewisse batteriebezogenen Elemente zu testen. Aber so wirklich geht das halt doch nicht.
Ich bin froh um alle Tester - viel Spass damit, hoffe es bringt was.
Grüsse forelleblau

**Comment by gepe2810** [comment]
Hallo,
habe die neue Version installiert.
solarlog.0 ist die 'alte' Version
solarlog.1 ist die neueste Version.
Hier ein Vergleich:

solarlog.0:
![image](https://user-images.githubusercontent.com/35432588/66696519-00f4ba00-eccd-11e9-8644-52629550e8dd.png)



solarlog.1:
![image](https://user-images.githubusercontent.com/35432588/66696549-33061c00-eccd-11e9-9dab-aae52b4723f4.png)

solarlog.1 status enthält einen neuen Datenpunkt consselfconsyieldday:
![image](https://user-images.githubusercontent.com/35432588/66696576-88dac400-eccd-11e9-811d-de1226e2821f.png)

Dieser scheint auch zu funktionieren.

Evtl. Abweichungen der Werte oben rühren daher, dass die Adapter mit unterschiedlichen Intervallen aktualisieren.

Grüsse
Gepe000

**Comment by forelleblau** [comment]
Hallo Gepe000
Danke vielmal, da scheint ja einiges zu funktionieren. 
Darstellung des Eigenverbrauchs bei den Status-Werten: check.
Holen der laufenden Batteriedaten:  check.
Holen der Batterie - Tagessummen: noch nicht check
Anlegen der Batterieobjekte: noch nicht so wie es gedacht wäre.
Eigentlich sollten alle Batteriewerte bei deinem VARTA-Gerät angelegt worden sein. Wenn ein Gerät vom Typ Batterie vorhanden ist, dann sollte alles beisammen sein. 
Das Anlegen eines generischen 'Battery' - Gerätes ist nur die Notlösung, wenn die Batterie Teil eines Hybrid- oder Kombisystems ist und die Werte im solarlog zwar geführt werden, nicht aber einem Gerät direkt zugeordnet sind - ja Batteriewerte sind in eigenen JSON-Objekten abgelegt und nicht direkt den Geräten zugeordnet.

Ich hab die selbe Frage wie fast immer: Kannst du mir ein Debug-Log vom Start des Adapters zur Verfügung stellen?

Herzlichen Dank fürs TEsten und liebe Grüsse
forelleblau

**Comment by gepe2810** [comment]
...klar.

[Log3.txt](https://github.com/forelleblau/ioBroker.solarlog/files/3721028/Log3.txt)

Grüsse
Gepe000

**Comment by forelleblau** [comment]
Danke vielmals. Gemäss deinem Log schein alles zu funktionieren, bis auf das korrekte Anlegen der Objekte zur Batterie. Wieso das schief lief konnte ich aber in meinem Geschreibsel nachvollziehen und korrigieren. Ebenso die fehlenden Werte für die Batterie - Tagessummen.
Der neue Code ist auf github, ohne neue Versionsnummer. Wenn du dein aktuelles 'Battery'-Device mit allen Objekten löschst und den Adapter neu von github installierst solltest du dann alle Batteriewerte bei deiner Varta im Device haben.

...vielleicht funktioniert ja diesmal schon alle ;-)

Danke fürs Testen und Grüsse aus der Werkstatt
forelleblau

**Comment by gepe2810** [comment]
....leider noch nicht ganz. Ich habe den Adapter installiert, die Instanz komplett gelöscht und neu angelegt, Hier das Ergebnis:

![image](https://user-images.githubusercontent.com/35432588/66777507-8644be00-eec9-11e9-9c72-2bb45659a1c4.png)


und gleich noch das Log-File: 
[Log4.txt](https://github.com/forelleblau/ioBroker.solarlog/files/3726095/Log4.txt)

Grüsse
Gepe000

**Comment by forelleblau** [comment]
...sorry...jetzt hast du mich aber auf den Punkt gebracht resp. auf drei fehlende davon. Manchmal scheitert es an den kleinen Dingen.
Eine neue Version der mains.js Datei, die nun INV.Varta Elemnent**.**XXX Objekte anlegen wird, ist bereits auf github.
Danke für deine Geduld und liebe Grüsse
forelleblau

**Comment by gepe2810** [comment]
...gerne doch :)


Gepe000

**Comment by gepe2810** [comment]
...jetzt sieht es gut aus. Super. Vielen Dank.



![Hardcopy1](https://user-images.githubusercontent.com/35432588/66780183-79779880-eed0-11e9-9914-8c5d79f09502.gif)

**Comment by forelleblau** [comment]
Dann mach ich mal einen letzten Check beim Rest und melde das ganze offiziell als neue Version.
Herzlichsten Dank für die super Unterstützung. Falls du wieder Mal einen Wunsch hast, jederzeit gerne wieder so.
Lieber Gruss forelleblau
