### ISSUE TITLE
please add travis for testing

### ISSUE THREAD

**Issue by Apollon77** [forelleblau/ioBroker.solarlog#2]

**Comment by Apollon77** [comment]
Great, you can check the info/warnings listed there :-)

https://travis-ci.org/forelleblau/ioBroker.solarlog/jobs/459921358#L802

**Comment by forelleblau** [comment]
...and get them away. Thanks a lot.
[https://travis-ci.org/forelleblau/ioBroker.solarlog/jobs/459950387#L1377](url)

**Comment by Apollon77** [comment]
awesome
