### ISSUE TITLE
Kein Adapter nach installation

### ISSUE THREAD

**Issue by Wello72** [forelleblau/ioBroker.solarlog#3]
Hallo,

ich wollte meinen SolarLog 500 in ioBroker einbinden. 

Nach der Installation direkt von git gibt es bei mir kein Instanz von Solarlog.

Muss ich diese selbst erstellen? 

Installiert ist die 0.0.2 vom Adapter.

Gruß
Rainer

**Comment by forelleblau** [comment]
Hallo Rainer
Wenn du den Adapter installiert hast, musst du auf der Adapter-Seite im ioBroker in der solarlog-Zeile mit dem entsprechenden Button eine Instanz erzeugen, das passiert nicht automatisch. Dann erscheint auch der config-Dialog wo die IP und das Abfrageintervall eingeben kannst. Nach dem Speichern werden die Objekte angelegt und mit Werten befüllt.
Herzliche Grüße 
Marcel

**Comment by Wello72** [comment]
Hallo Marcel,

danke, perfekt... Alles probiert, nur diesen einen Knopf nicht.
Daten werden ausgelesen und ins zugehörige Objekt geschrieben.
Dann mach ich mal an einen View.

Danke nochmals
Schönen Gruß
Rainer
